AppDev/Models/Book.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace AppDev.Models
{
	public class Book
	{
		[Key]
		public int Id { get; set; }
		public string Title { get; set; }
		public string Description { get; set; }
		public string Author { get; set; }
		[Range(1, 1000)]
		public double Price { get; set; }
		[ValidateNever]
		public int CategoryId { get; set; }
		[ForeignKey("CategoryId")]
		[ValidateNever]
		public Category Category { get; set; }

	}
}

AppDev/Models/Category.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace AppDev.Models
{
	public class Category
	{
        [Key]
        public int Id { get; set; }
        [Required]
        [DisplayName("Category Name")]
        public string Name { get; set; }
        public string Description { get; set; }
        [DisplayName("Display Order")]
        [Range(1, 100)]
        public int DisplayOrder { get; set; }
    }
}

AppDev/Models/ErrorViewModel.cs
namespace AppDev.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AppDev/Controllers/BookController.cs
using AppDev.Data;
using AppDev.Models;
using Microsoft.AspNetCore.Mvc;

namespace AppDev.Controllers
{
	public class BookController: Controller
	{
		private readonly ApplicationDBContext _dbContext;
		public BookController(ApplicationDBContext dbContext)
		{
			_dbContext = dbContext;
		}
		public IActionResult Index()
		{
			List<Book> books = _dbContext.Books.ToList();
			return View(books);
		}
		public IActionResult CreateUpdate(int? id)
		{
			Book book = new Book();
			if (id == null || id == 0)
			{
				//Create new Book
				return View(book);
			}
			else
			{
				//Update a Book
				book = _dbContext.Books.Find(id);
				return View(book);
			}

		}
		[HttpPost]

		public IActionResult CreateUpdate(Book book)
		{

			if (ModelState.IsValid)
			{
				if (book.Id == 0)
				{
					_dbContext.Books.Add(book);
					TempData["success"] = "Book created succesfully";
				}
				else
				{
					_dbContext.Books.Update(book);
					TempData["success"] = "Book updated succesfully";
				}
				_dbContext.SaveChanges();
				return RedirectToAction("Index");
			}

			return View();

		}
		public IActionResult Delete(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}
			Book? book = _dbContext.Books.Find(id);
			if (book == null)
			{
				return NotFound();
			}
			return View(book);
		}
		[HttpPost]
		public IActionResult Delete(Book book)
		{
			_dbContext.Books.Remove(book);
			_dbContext.SaveChanges();
			TempData["success"] = "Book deleted succesfully";
			return RedirectToAction("Index");
		}
	}
}

AppDev/Controllers/CategoryController.cs
using AppDev.Data;
using AppDev.Models;
using AppDev.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;

namespace AppDev.Controllers
{
	public class CategoryController : Controller
	{
		private readonly ICategoryRepository CategoryRepository;
		public CategoryController(ICategoryRepository categoryRepository)
		{
			CategoryRepository = categoryRepository;
		}
		public IActionResult Index()
		{
			List<Category> categories = CategoryRepository.GetAll().ToList();
			return View(categories);
		}
		public IActionResult Create()
		{
			return View();
		}
		[HttpPost]
		public IActionResult Create(Category category)
		{

			if (category.Name == category.Description)
			{
				ModelState.AddModelError("Description", "Name can not be equal to Description");
			}
			if (ModelState.IsValid)
			{
				CategoryRepository.Add(category);
				CategoryRepository.Save();
				TempData["success"] = "Category Created successfully";
				return RedirectToAction("Index");
			}
			return View();
		}
		public IActionResult Edit(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}
			Category? category = CategoryRepository.Get(c => c.Id == id);
			//category = _dbContext.Categories.FirstOrDefault(c => c.Id == id);
			if (category == null)
			{
				return NotFound();
			}
			return View(category);
		}
		[HttpPost]
		public IActionResult Edit(Category category)
		{
			if (ModelState.IsValid)
			{
				CategoryRepository.Update(category);
				CategoryRepository.Save();
				TempData["success"] = "Category Updated successfully";
				return RedirectToAction("Index");
			}
			return View();
		}
		public IActionResult Delete(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}
			Category? category = CategoryRepository.Get(c => c.Id == id);
			if (category == null)
			{
				return NotFound();
			}
			return View(category);
		}
		[HttpPost]
		public IActionResult Delete(Category category)
		{
			CategoryRepository.Delete(category);
			CategoryRepository.Save();
			TempData["success"] = "Category Deleted successfully";
			return RedirectToAction("Index");
		}
	}
}

AppDev/Controllers/HomeController.cs
using AppDev.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AppDev.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AppDev/Views/Book/CreateUpdate.cshtml
@model Book
<h1> @(Model.Id == 0 ? "Create" : "Edit") a Book</h1>
<form method="post">
    <div class="border p-3 mt-4">
        <input asp-for="Id" hidden />
        <div class="row mb-3">
            <label asp-for="Title"></label>
            <input asp-for="Title">
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="row mb-3">
            <label asp-for="Description"></label>
            <input asp-for="Description">
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="row mb-3">
            <label asp-for="Author"></label>
            <input asp-for="Author">
            <span asp-validation-for="Author" class="text-danger"></span>
        </div>
        <div class="row mb-3">
            <label asp-for="Price"></label>
            <input asp-for="Price">
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>
        <div class="row mb-3">
            <label asp-for="CategoryId"></label>
            <input asp-for="CategoryId">
            <span asp-validation-for="CategoryId" class="text-danger"></span>
        </div>

        <div class="btn group" role="group">
            @if (Model.Id == 0)
            {
                <button type="submit" class="btn btn-primary">Create</button>
            }
            else
            {
                <button type="submit" class="btn btn-primary">Update</button>
            }

            <a asp-controller="Book" asp-action="Index" class="btn btn-primary">
                Back to List
            </a>
        </div>
    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

AppDev/Views/Book/Delete.cshtml
@model Book
<h1> Delete a Book</h1>
<form method="post">
    <div class="border p-3 mt-4">
        <div class="mb-3 row">
            <label asp-for="Title"></label>
                <input asp-for="Title" disabled>
        </div>
        <div class="mb-3 row">
            <label asp-for="Description"></label>
            <input asp-for="Description" disabled>
        </div>
        <div class="mb-3 row">
            <label asp-for="Author"></label>
            <input asp-for="Author" disabled>
        </div>
        <div class="mb-3 row">
            <label asp-for="Price"></label>
            <input asp-for="Price" disabled>
        </div>
        <div class="mb-3 row">
            <label asp-for="CategoryId"></label>
            <input asp-for="CategoryId" disabled>
        </div>
            <button type="submit" class="btn btn-primary">Delete</button>
        <a asp-controller="Book" asp-action="Index" class="btn btn-primary">Back to List</a>
    </div>
</form>

AppDev/Views/Book/Index.cshtml
@model List<Book>
<partial name="_Notification" />
<div class="row pt-4 pb-4">
	<div class="col-9">
		<h2>List of Books</h2>
	</div>
	<div class="col-3">
		<a asp-controller="Book" asp-action="CreateUpdate" class="btn btn-primary">Create new Book</a>
	</div>
</div>
<div>
	<table class="table table-bordered">
		<thead>

			<tr>
				<th>Book Title</th>
				<th>Description</th>
				<th>Author</th>
				<th>Price</th>
				<th>Category</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var Book in Model)
			{
				<tr>
					<td>@Book.Title</td>
					<td>@Book.Description</td>
					<td>@Book.Author</td>
					<td>@Book.Price</td>
					<td></td>
					<td>
						<div class="btn group" role="group">
							<a asp-controller="Book" asp-action="CreateUpdate" asp-route-id="@Book.Id" class="btn btn-primary">
								<i class="bi bi-pencil"></i> Edit
							</a>
							<a asp-controller="Book" asp-action="Delete" asp-route-id="@Book.Id" class="btn text-danger">
								<i class="bi bi-trash-fill"></i> Delete
							</a>
						</div>
					</td>
				</tr>
			}
		</tbody>
	</table>
</div>

AppDev/Views/Category/Create.cshtml
@model Category
<h1>Create a category</h1>
<form method="post">
    <div class="border p-3 mt-4">
        <div class="mb-3 row">
            <label asp-for="Name"></label>
            <input asp-for="Name">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3 row">
            <label asp-for="Description"></label>
            <input asp-for="Description">
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="mb-3 row">
            <label asp-for="DisplayOrder"></label>
            <input asp-for="DisplayOrder">
            <span asp-validation-for="DisplayOrder" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <a asp-controller="Category" asp-action="Index" class="btn btn-primary">Back to List</a>
    </div>
</form>
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

AppDev/Views/Category/Delete.cshtml
@model Category
<h1>Delete a category</h1>
<form method="post">
    <div class="border p-3 mt-4">
        <div class="mb-3 row">
            <label asp-for="Name"></label>
            <input asp-for="Name" disabled>
        </div>
        <div class="mb-3 row">
            <label asp-for="Description"></label>
            <input asp-for="Description" disabled>
        </div>
        <div class="mb-3 row">
            <label asp-for="DisplayOrder"></label>
            <input asp-for="DisplayOrder" disabled>
        </div>
        <button type="submit" class="btn btn-danger">Delete</button>
        <a asp-controller="Category" asp-action="Index" class="btn btn-primary">Back to List</a>
    </div>
</form>

AppDev/Views/Category/Details.cshtml
<h1>Categories Details</h1>

AppDev/Views/Category/Edit.cshtml
@model Category
<h1>Edit a category</h1>
<form method="post">
    <div class="border p-3 mt-4">
        <div class="mb-3 row">
            <label asp-for="Name"></label>
            <input asp-for="Name">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3 row">
            <label asp-for="Description"></label>
            <input asp-for="Description">
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="mb-3 row">
            <label asp-for="DisplayOrder"></label>
            <input asp-for="DisplayOrder">
            <span asp-validation-for="DisplayOrder" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Edit</button>
        <a asp-controller="Category" asp-action="Index" class="btn btn-primary">Back to List</a>
    </div>
</form>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

AppDev/Views/Category/Index.cshtml
@model List<Category>
<partial name="_Notification" />
<div class="row pt-4 pb-4">
	<div class="col-6">
		<h2>List of Categories</h2>
	</div>
	<div class="col-6">
		<a asp-controller="Category" asp-action="Create" class="btn btn-primary">Create a Category</a>
	</div>
</div>

<div>
	<table class="table table-bordered">
		<thead>
			<tr>
				<td>Category Name</td>
				<td>Description</td>
				<td>Display Order</td>
			</tr>
		</thead>
		<tbody>
			@foreach (var category in Model)
			{
				<tr>
					<td>@category.Name</td>
					<td>@category.Description</td>
					<td>@category.DisplayOrder</td>
					<td>
						<a asp-controller="Category" asp-action="Edit" asp-route-id="@category.Id" class="btn btn-primary">Edit</a>
						<a asp-controller="Category" asp-action="Delete" asp-route-id="@category.Id" class="btn btn-danger">Delete</a>
					</td>
				</tr>
			}
		</tbody>
	</table>
</div>

AppDev/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AppDev/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppDev</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppDev.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppDev</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Book</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AppDev - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AppDev/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.success('@TempData["success"]');
	</script>
}